FROM bitnami/spark:latest

USER root

# Install OpenJDK
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
      sudo \
      curl \
      vim \
      openjdk-17-jdk \
      ssh && \
    apt-get clean

# Set path related pyspark
ENV PYSPARK_PYTHON python3

# Set JAVA_HOME
ENV JAVA_HOME /usr/lib/jvm/java-17-openjdk-amd64/
RUN export JAVA_HOME

# Set PYTHON_PATH
ENV PYTHONPATH /opt/bitnami/spark/python/:$PYTHONPATH
RUN export PYTHONPATH