version: "3"

x-spark-common: &spark-common
    image: bitnami/spark:latest
    volumes:
        - ./jobs:/opt/bitnami/spark/jobs
    networks:
        - vnainternship

services:
    sleek-airflow:
        image: airflow:latest

        volumes:
            - ./airflow:/opt/airflow

        ports:
            - "8080:8080"

        command: airflow standalone

    # spark-master:
    #     <<: *spark-common
    #     command: bin/spark-class org.apache.spark.deploy.master.Master
    #     ports:
    #         - "9090:8080"
    #         - "7077:7077"

    # spark-worker:
    #     <<: *spark-common
    #     command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    #     depends_on:
    #         - spark-master
    #     environment:
    #         SPARK_MODE: worker
    #         SPARK_WORKER_CORES: 2
    #         SPARK_WORKER_MEMORY: 1g
    #         SPARK_MASTER_URL: spark://spark-master:7077

    postgres-db:
        image: postgres:16
        ports:
            - 5434:5432
        volumes:
            - postgres_data:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: nhanbui
            POSTGRES_DB: postgres
        networks:
            - vnainternship

networks:
    vnainternship:
